---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.23"
  amd64: "ghcr.io/home-assistant/amd64-base:3.23"
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: traefik"
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/traefik
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/traefik/README.md
  org.opencontainers.image.created: "2026-01-24T22:02:47Z"
  org.opencontainers.image.revision: cb56104cc5944629a3a2dcf2ce8fa55bfd29aa6e
  org.opencontainers.image.version: 5.0.0
