build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.15"
  amd64: "ghcr.io/home-assistant/amd64-base:3.15"
  armhf: "ghcr.io/home-assistant/armhf-base:3.15"
  armv7: "ghcr.io/home-assistant/armv7-base:3.15"
  i386: "ghcr.io/home-assistant/i386-base:3.15"
labels:
  org.opencontainers.image.title: "Home Assistant Unofficial Add-on: Traefik"
  org.opencontainers.image.description: "Rclone bundled as an Home Assistant add-on."
  org.opencontainers.image.source: "https://github.com/bluemaex/home-assistant-addons/"
  org.opencontainers.image.licenses: "MIT"
args:
  TRAEFIK_VERSION: 2.8.1
