---
build_from:
  aarch64: "ghcr.io/home-assistant/aarch64-base:3.19"
  amd64: "ghcr.io/home-assistant/amd64-base:3.19"
  armv7: "ghcr.io/home-assistant/armv7-base:3.19"
codenotary:
  signer: homeassistant@blmx.de
  base_image: notary@home-assistant.io
labels:
  maintainer: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.authors: "bluemaex <homeassistant@blmx.de>"
  org.opencontainers.image.licenses: "MIT License"
  org.opencontainers.image.title: 'Home Assistant Unofficial Add-on: traefik'
  org.opencontainers.image.url: https://github.com/bluemaex/home-assistant-addons
  org.opencontainers.image.source: https://github.com/bluemaex/home-assistant-addons/traefik
  org.opencontainers.image.documentation: https://github.com/bluemaex/home-assistant-addons/traefik/README.md
  org.opencontainers.image.created: "2023-12-31T14:52:03Z"
  org.opencontainers.image.revision: 25b72359469ec11ae5010475f97e451b74595379
  org.opencontainers.image.version: 4.2.2
